export const mainL = {
  'Ru': {
    title: 'Органайзер',
    name: 'Название',
    modal_title: 'Новая задача',
    add_task: 'Добавить задание',
    add: 'Добавить',
    return: 'Назад',
    delete: 'Удалить',
    edit: 'Редактировать',
    exclusivity: 'Исключаемость',
    compressibility: 'Сжимаемость',
    urgent: 'Срочное',
    no_entries: 'Нет записей',
    estimate: 'Расчитать',
    add_compl: 'Добавить сложную задачу',
    id: 'ИД',
    dedline: 'Дата выполнения',
    labour: 'Трудоемкость',
    start: 'Начало',
    end: 'Конец',
    cal_start: 'Дата начала',
    cal_end: 'Дата окончания',
    wrong: 'неправильно',
    edit_task: 'Редактирование задачи',
    insert: 'Введите',
    rand_num: 'любое число',
    task: 'Задания',
    spr_importance: 'степень важности',
    spr_labour: 'обьем работ',
    stor_compl_tasks: 'Сдожные задачи',
    schedule: 'Режим дня',
    statistic: 'Статистика',
    preference: 'Настройки',
    importance: 'Важность',
    job: 'Работа',
    done: 'Готово',
    weekdays: 'Будни',
    weekends: 'Выходные'
  },
  'En': {
    title: 'Task Meneger',
    modal_title: 'New task',
    add_task: 'Add task',
    add: 'Add',
    return: 'Return',
    delete: 'Delete',
    edit: 'Edit',
    exclusivity: 'Exclusivity',
    compressibility: 'Compressibility',
    urgent: 'Ugent',
    no_entries: 'No entries',
    estimate: 'Estimate',
    add_compl: 'Add complicated task',
    id: 'id',
    dedline: 'dedline',
    labour: 'labour',
    start: 'start',
    end: 'end',
    cal_start: 'Start Time',
    cal_end: 'End Time',
    wrong: 'wrong',
    edit_task: 'Edit task',    
    insert: 'insert',
    name: 'name',
    rand_num: 'any number',
    task: 'task',
    spr_importance: 'degree of importance',
    spr_labour: 'scope of work',
    stor_compl_tasks: 'Advanced tasks',
    schedule: 'Daily mode',
    statistic: 'Statistics',
    preference: 'Settings',
    importance: 'Importance',
    job: 'Job',
    
    done: 'Готово',
    weekdays: 'weekdays',
    weekends: 'weekends'
  },
  'de-DE': {
    title: 'Task Meneger', 
    modal_title: 'Neue Aufgabe',
    add_task: 'Aufgabe hinzufügen',
    add: 'Hinzufügen',
    return: 'Zurück',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    exclusivity: 'Exklusivität',
    compressibility: 'Kompressibilität',
    urgent: 'Ugent',
    no_entries: 'Keine Einträge',
    estimate: 'Schätzung',
    add_compl: 'Komplizierte Aufgabe hinzufügen',    
    id: 'id',
    dedline: 'dedline',
    labour: 'Arbeit',
    start: 'start',
    end: 'Ende',
    cal_start: 'Start Time',
    cal_end: 'End Time',
    wrong: 'falsch',
    edit_task: 'Aufgabe bearbeiten',    
    insert: 'Einfügen',
    name: 'name',
    rand_num: 'any number',
    task: 'Aufgaben',
    spr_importance: 'Wichtigkeitsgrad',
    spr_labour: 'Arbeitsumfang',
    stor_compl_tasks: 'Erweiterte Aufgaben',
    schedule: 'Täglicher Modus',
    statistic: 'Statistik',
    preference: 'Einstellungen',

    importance: 'Importance',
    
    job: 'Job',
    done: 'Готово',
    weekdays: 'weekdays',
    weekends: 'weekends'
  },
  'es': {
    title: 'Task Meneger',
    modal_title: 'Nueva tarea',
    add_task: 'Agregar tarea',
    add: 'Agregar',
    return: 'Return',
    delete: 'Eliminar',
    edit: 'Editar',
    exclusivity: 'Exclusividad',
    compressibility: 'Compresibilidad',
    urgent: 'Ugent',
    no_entries: 'Sin entradas',
    estimate: 'Estimación',
    add_compl: 'Agregar tarea complicada',    
    id: 'id',
    dedline: 'dedline',
    labour: 'labour',
    start: 'inicio',
    end: 'fin',
    cal_start: 'Start Time',
    cal_end: 'End Time',
    wrong: 'malo',
    edit_task: 'Editar tarea',    
    insert: 'insert',
    name: 'nombre',
    rand_num: 'cualquier número',
    task: 'tarea',
    spr_importance: 'grado de importancia',
    spr_labour: 'alcance del trabajo',
    stor_compl_tasks: 'Tareas avanzadas',
    schedule: 'Modo diario',
    statistic: 'Estadísticas',
    preference: 'Configuración',

    importance: 'Importance',
    job: 'Job',
    weekdays: 'weekdays',
    weekends: 'weekends'
  },
  'fr': {
    title: 'Органайзер',
    modal_title: 'Nouvelle tâche',
    add_task: 'Ajouter une tâche',
    add: 'Ajouter',
    return: 'Retour',
    delete: 'Delete',
    edit: 'Edit',
    exclusivity: 'Exclusivité',
    compressibility: 'Compressibilité',
    urgent: 'Ugent',
    no_entries: 'Aucune entrée',
    estimate: 'Estimation',
    add_compl: 'Ajouter une tâche compliquée',
    id: 'id',
    dedline: 'dedline',
    labour: 'labour',
    start: 'démarrer',
    end: 'fin',
    cal_start: 'Heure de début',
    cal_end: 'End Time',
    wrong: 'faux',
    edit_task: 'Editer la tâche',    
    insert: 'insérer',
    name: 'nom',
    rand_num: 'un nombre quelconque',
    task: 'tâche',
    spr_importance: 'degré d`importance',
    spr_labour: 'étendue du travail',
    stor_compl_tasks: 'Tâches avancées',
    schedule: 'Mode quotidien',
    statistic: 'Statistiques',
    preference: 'Paramètres',

    importance: 'Importance',
    job: 'Job',
    done: 'Готово',
    weekdays: 'weekdays',
    weekends: 'weekends'
  },
  'zh-Hans': {
    title: '任务存储',
    modal_title: '新任务',
    add_task: '添加任务',
    add: '添加',
    return: '返回',
    delete: '删除',
    edit: '编辑',
    exclusivity: '排他性',
    compressibility: '可压缩性',
    urgent: '紧急',
    no_entries: '无条目',
    estimate: '估算',
    add_compl: '添加复杂的任务',    
    id: 'id',
    dedline: 'dedline',
    labour: '劳工”',
    start: '开始',
    end: '结束',
    cal_start: '开始时间',
    cal_end: '结束时间',
    wrong: '错误',
    edit_task: '编辑任务',    
    insert: '插入',
    name: '名称',
    rand_num: '任何数字',
    task: '任务',
    spr_importance: '重要程度',
    spr_labour: '工作范围',
    stor_compl_tasks: '高级任务',
    schedule: '每日模式',
    statistic: '统计',
    preference: '设置',

    importance: 'Importance',
    job: 'Job',
    done: 'Готово',
    weekdays: 'weekdays',
    weekends: 'weekends'
  },
}