export const C_CAL = 
{  
  SET_CAL: 'SET_CAL',
  MANAGE_SIMPLE_TASK: 'MANAGE_SIMPLE_TASK',
  ADD_COMPLICATED_TASK: 'ADD_COMPLICATED_TASK',
  REMOVE_COMPLICATED_TASK: 'REMOVE_COMPLICATED_TASK',
  EDIT_COMPLICATED_TASK: 'EDIT_COMPLICATED_TASK',
  SET_SCHEDULE: 'SET_SCHEDULE',
  SET_WEEKDAY_PATTERN: 'SET_WEEKDAY_PATTERN',
  SET_WEEKEND_PATTERN: 'SET_WEEKEND_PATTERN',
  CHOSE_DAY: 'CHOSE_DAY',
  ADD_QUICK_TASK: 'ADD_QUICK_TASK',
  REMOVE_QUICK_TASK: 'REMOVE_QUICK_TASK'   
}
