export const C_INFO = 
{  
  CLEAR: 'CLEAR',
  SET: 'SET',
  WRITE_THROUGH_PERIODS: 'WRITE_THROUGH_PERIODS',
  SET_DEDLINE_POSTPONEMENT: 'SET_DEDLINE_POSTPONEMENT',
  /*
  SET_DECISION_ERROR_ID: 'SET_DECISION_ERROR_ID',
  SET_THROUGH_PERIOD: 'SET_THROUGH_PERIOD',
  SET_MAX_COUNT_DISCRETE_PERIODS: 'SET_MAX_COUNT_DISCRETE_PERIODS',
  */
}
