export const C_TASK = 
{  
  CHOSE_COMPLICATED_TASK: 'CHOSE_COMPLICATED_TASK',
  ADD_COMPLICATED_TASK: 'ADD_COMPLICATED_TASK',
  REMOVE_COMPLICATED_TASK: 'REMOVE_COMPLICATED_TASK',
  EDIT_COMPLICATED_TASK: 'EDIT_COMPLICATED_TASK',
}
