export const C_UI = 
{  
  TOGGLE_MODAL_ADD_SIMPLE_TASK: 'TOGGLE_MODAL_ADD_SIMPLE_TASK',
  TOGGLE_MODE_MODAL_ADD_SIMPLE_TASK: 'TOGGLE_MODE_MODAL_ADD_SIMPLE_TASK',
  TOGGLE_MODE_MODAL_ADD_COMPLICATED_TASK: 'TOGGLE_MODE_MODAL_ADD_COMPLICATED_TASK',
  OK_MODAL_ADD_SIMPLE_TASK: 'OK_MODAL_ADD_SIMPLE_TASK',
  CANCEL_MODAL_ADD_SIMPLE_TASK: 'CANCEL_MODAL_ADD_SIMPLE_TASK',
  TOGGLE_MODAL_ADD_COMPLICATED_TASK: 'TOGGLE_MODAL_ADD_COMPLICATED_TASK',
  OK_MODAL_ADD_COMPLICATED_TASK: 'OK_MODAL_ADD_COMPLICATED_TASK',
  CANCEL_MODAL_ADD_COMPLICATED_TASK: 'CANCEL_MODAL_ADD_COMPLICATED_TASK',
  TOGGLE_PATTERN_MODAL: 'TOGGLE_PATTERN_MODAL',
  TOGGLE_MODE_PATTERN_MODAL: 'TOGGLE_MODE_PATTERN_MODAL',
  TOGGLE_INFO_MODAL: 'TOGGLE_INFO_MODAL',
}

