export const C_UX = 
{  
  CHANGE_LANG: 'CHANGE_LANG',
  COMPLETE_FILL_PATTERN: 'COMPLETE_FILL_PATTERN',
  SET_AGGRESSIVENESS_EXCLUDE: 'SET_AGGRESSIVENESS_EXCLUDE',
  SET_AGGRESSIVENESS_SQUEEZING: 'SET_AGGRESSIVENESS_SQUEEZING',
  SET_AGGRESSIVENESS_PERMUTATION: 'SET_AGGRESSIVENESS_PERMUTATION',
  SET_MIN_TASK_TIME: 'SET_MIN_TASK_TIME'
}
